name: Security check - Bandit

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Run bandit
      uses: VCTLabs/bandit-report-artifacts@master
      with:
        project_path: asterisk
        ignore_failure: true
